name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Lint Backend
        run: |
          cd backend
          npx eslint .

      - name: Lint Frontend
        run: |
          cd frontend
          npx eslint .
